swagger: "2.0"
paths:
  tag:
    - "post"
    - "board"
  /post:
    post:
      summary: Save Post
      description: 게시물 올리기
      produces:
        -application/json
      responses:
        200:
          description: Ok
        409:
          description: Not match user token
        422:
          description: No have args or not match args

    get:
      summary: Get all posts
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameter:
        -in: "body"
      responses:
        200:
          description: OK

  /post/:id:
    get:
      summary: Get post
      description: 하나의 게시물만 리턴
      produces:
        -application/json
      parameter:
      responses:
        200:
          description: Ok

    put:
      summary: Modified post
      description:
      produces:
        -application/json
      responses:
        200:
          description: Ok

    delete:
      summary: Delete post
      description:
      produces:
        -application/json
      responses:
        200:
          description: Ok

