swagger: 2.0
# info:
  # title: fff
  # tag:
  #   name: Board
  #   description: Board post 
    # externalDocs:
    #   description: Find out more about github
    #   url: https://github.com/kdm-korea/nodeBoard

paths:
  /post:
    post:
      tags:
        - Board
      summary: Add new post
      description: "Create post"
      consumes:
        -application/json
      produces:
        -application/json
      parameters:
        - name: token
          in: header
          description: "token to be passed as a header"
          default: "ZjE4YjMxNmY3OGEzNDMyN2JiYjJmYTQwMDBjODg4OWM="
          required: true
          type: string
        # - in: headers
        #   name: token
        #   description: 'jwt token'
        #   type: apiKey
        #   value: 'Bearer aaaa.bbbb.cccc'
        # - in: body
        #   name: Add new post
        #   schema:
        #     type: application/json
        #     properties:
        #       title:
        #         type: String
        #       contents:
        #         type: String
        #     example: 
        #       title: exmaple title
        #       contents: example contents
      responses:
        200:
          description: Ok
        409:
          description: Not match user token
        422:
          description: No have args or not match args

    get:
      tags:
        - "Board"
      summary: Get all posts
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameter:
        -in: "body"
      responses:
        200:
          description: OK
        409:
          description: No hvae args or not match args
  /post/:id:
    get:
      tags:
        - "Board"
      summary: Get post
      description: 하나의 게시물만 리턴
      produces:
        -application/json
      parameter:
      responses:
        200:
          description: Ok
    put:
      tags:
        - "Board"
      summary: Modified post
      description:
      produces:
        -application/json
      responses:
        200:
          description: Ok
    delete:
      tags:
        - "Board"
      summary: Delete post
      description:
      produces:
        -application/json
      responses:
        200:
          description: Ok