# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build nodeJs 13

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn build
      run:  |
        yarn
        yarn dev
#     - run: npm test
      env:
        DB_USERNAME: ${{secrets.DB_USERNAME}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_DATABASE_NAME: ${{secrets.DB_DATABASE_NAME}}
        DB_HOST_IP: ${{secrets.DB_HOST_IP}}
        DB_DIALECT: ${{secrets.DB_DIALECT}}
        JWT_KEY: ${{secrets.JWT_KEY}}
        CI: true
